app = "download-v1-app"

[build]
  image = "download-v1-app:latest"

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

[[mounts]]
  source = "downloads"
  destination = "/app/downloads"
