# fly.toml app configuration file generated for download-v1-app on 2025-04-04T16:40:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'download-v1-app'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  GUNICORN_MAX_REQUESTS = '1000'
  GUNICORN_MAX_REQUESTS_JITTER = '100'
  GUNICORN_TIMEOUT = '120'
  GUNICORN_WORKERS = '2'
  LOG_LEVEL = 'info'
  PORT = '8080'
  PYTHONDONTWRITEBYTECODE = '1'
  PYTHONUNBUFFERED = '1'
  YOUTUBE_COOKIES = "# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tTRUE\t1735689600\tGPS\t1\n.youtube.com\tTRUE\t/\tTRUE\t1735689600\tVISITOR_INFO1_LIVE\tW5qjHg-5qYQ\n.youtube.com\tTRUE\t/\tTRUE\t1735689600\tYSC\tnMJqLV_8y0A\n.youtube.com\tTRUE\t/\tTRUE\t1735689600\tPREF\tf4=4000000&tz=Europe.London"

[[mounts]]
  source = 'downloads'
  destination = '/app/downloads'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
  https = false
