app = "download-v1-app"
primary_region = "ams"

[env]
  PORT = "8080"

[processes]
  app = "gunicorn app:app --bind 0.0.0.0:8080 --worker-class uvicorn.workers.UvicornWorker --workers 4"

[http]
  internal_port = 8080

[[mounts]]
  source = "downloads"
  destination = "/app/downloads"
