name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: download-v1-app

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create Fly app
        run: |
          flyctl apps create $FLY_APP_NAME --org personal || true
          flyctl volumes create downloads --size 10 --app $FLY_APP_NAME || true
      
      - name: Deploy to fly.io
        run: |
          flyctl deploy --app $FLY_APP_NAME --local-only
